# Generated by Django 5.1.5 on 2026-09-22 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyLeague',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sleeper_league_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'fantasy_leagues',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FantasyRoster',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sleeper_roster_id', models.IntegerField()),
                ('owner_sleeper_id', models.CharField(blank=True, max_length=100, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'fantasy_rosters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FantasyRosterPlayer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'fantasy_roster_players',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sleeper_id', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.FloatField(blank=True, null=True)),
                ('team_id', models.IntegerField(blank=True, null=True)),
                ('headshot_url', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('injury_status', models.CharField(blank=True, max_length=100, null=True)),
                ('years_exp', models.IntegerField(blank=True, null=True)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('college', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('owned_percentage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'players',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserLeagueConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('external_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_connections', to='leagues.fantasyleague')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'league'), name='unique_user_league_connection')],
            },
        ),
    ]
