# Generated by Django 5.1.5 on 2026-09-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleagueconnection',
            name='platform',
            field=models.CharField(choices=[('sleeper', 'Sleeper'), ('yahoo', 'Yahoo'), ('espn', 'ESPN')], max_length=20),
        ),
    ]
