# Generated by Django 5.1.5 on 2026-09-30 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_alter_userleagueconnection_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YahooAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('yahoo_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yahoo_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaguePlatformIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('external_id', models.CharField(max_length=255)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_identities', to='leagues.fantasyleague')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('platform', 'external_id'), name='unique_platform_league_external_id'), models.UniqueConstraint(fields=('league', 'platform'), name='unique_league_platform')],
            },
        ),
        migrations.CreateModel(
            name='PlayerPlatformIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('external_id', models.CharField(max_length=255)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_identities', to='leagues.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('platform', 'external_id'), name='unique_platform_player_external_id'), models.UniqueConstraint(fields=('player', 'platform'), name='unique_player_platform')],
            },
        ),
        migrations.CreateModel(
            name='RosterPlatformIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('external_id', models.CharField(max_length=255)),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_identities', to='leagues.fantasyroster')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('platform', 'external_id'), name='unique_platform_roster_external_id'), models.UniqueConstraint(fields=('roster', 'platform'), name='unique_roster_platform')],
            },
        ),
    ]
