# Generated by Django 5.1.5 on 2026-10-08 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_yahooaccount_leagueplatformidentity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('settings_hash', models.CharField(max_length=64, unique=True)),
                ('settings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scoring_profiles',
            },
        ),
        migrations.CreateModel(
            name='FantasyProjection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('season', models.IntegerField()),
                ('week', models.IntegerField()),
                ('projected_fantasy_points', models.FloatField()),
                ('status', models.CharField(default='projected', max_length=20)),
                ('model_version', models.CharField(default='v1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fantasy_projections', to='leagues.player')),
                ('scoring_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projections', to='leagues.scoringprofile')),
            ],
            options={
                'db_table': 'fantasy_projections',
                'indexes': [models.Index(fields=['scoring_profile', 'season', 'week'], name='projection_lookup_idx'), models.Index(fields=['player', 'season', 'week'], name='player_projection_idx')],
                'constraints': [models.UniqueConstraint(fields=('player', 'scoring_profile', 'season', 'week', 'model_version'), name='unique_fantasy_projection')],
            },
        ),
    ]
