
# Generated by Django 5.1.5 on 2026-10-08

from django.db import migrations, models


def remove_duplicate_projections(apps, schema_editor):
    """
    Keep the lowest-ID row for each player, season, week,
    and model version.
    """
    schema_editor.execute(
        """
        DELETE FROM fantasy_projections AS a
        USING fantasy_projections AS b
        WHERE a.id > b.id
          AND a.player_id = b.player_id
          AND a.season = b.season
          AND a.week = b.week
          AND a.model_version = b.model_version;
        """
    )


class Migration(migrations.Migration):

    dependencies = [
        ("leagues", "0004_scoringprofile_fantasyprojection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fantasyprojection",
            name="scoring_profile",
        ),

        migrations.RunPython(
            remove_duplicate_projections,
            reverse_code=migrations.RunPython.noop,
        ),

        # The old index may already be absent from the database.
        # Drop it safely while keeping Django's migration state aligned.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP INDEX IF EXISTS projection_lookup_idx;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name="fantasyprojection",
                    name="projection_lookup_idx",
                ),
            ],
        ),

        migrations.AddIndex(
            model_name="fantasyprojection",
            index=models.Index(
                fields=["season", "week"],
                name="projection_lookup_idx",
            ),
        ),

        migrations.AddConstraint(
            model_name="fantasyprojection",
            constraint=models.UniqueConstraint(
                fields=(
                    "player",
                    "season",
                    "week",
                    "model_version",
                ),
                name="unique_fantasy_projection",
            ),
        ),

        migrations.DeleteModel(
            name="ScoringProfile",
        ),
    ]
