# Generated by Django 5.1.5 on 2026-09-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='espn_username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sleeper_username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='yahoo_username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
